### ISSUE TITLE
GISD 2018

### ISSUE THREAD

**Issue by dimitrirosto** [abhshkdz/ai-deadlines#122]
Suggest GISD 2018 to the list of AI Conferences. Discussions focus on using AI in cybersecurity and cybercrime. [Event link](http://www.htbridge.com/gisd)

**Comment by abhshkdz** [comment]
Thanks @dimitrirosto. But looking to strictly limit to top-tier conferences as per conferenceranks.com, so not merging this, sorry. I might reconsider later.
