### ISSUE TITLE
Bug with Negative GMT timezones

### ISSUE THREAD

**Issue by khosravipasha** [abhshkdz/ai-deadlines#161]
If the timezone of the dealine is GMT-\*\*, the website is somehow ignoring the negative and shows the deadline as GMT+\*\*. For example, for the upcoming UAI deadline the [data](https://github.com/abhshkdz/ai-deadlines/blob/gh-pages/_data/conferences.yml#L9) correctly shows GMT -11:00 timezone, however on the website it is treating the deadline as GMT +11:00, hence the deadline showed on the website is off by 22 hours.

This also happens with other conferences that have negative GMT deadlines, [ECML-PKDD](https://github.com/abhshkdz/ai-deadlines/blob/gh-pages/_data/conferences.yml#L53), and [EMNLP-IJCNLP](https://github.com/abhshkdz/ai-deadlines/blob/gh-pages/_data/conferences.yml#L85).

**Comment by abhshkdz** [comment]
Thanks! Turns out this wasn't a bug: https://github.com/moment/moment-timezone/issues/167, just counterintuitive design. Added support for the more intuitive version.

**Comment by khosravipasha** [comment]
Awesome, thanks for the quick fix. I knew timezones are always tricky, learned something new today.
