### ISSUE TITLE
where to find my own webpage?

### ISSUE THREAD

**Issue by xuxy09** [abhshkdz/ai-deadlines#163]
Dear author,

I have forked your code and edited the conference list. Could you please let me know where to find my own webpage?

**Comment by abhshkdz** [comment]
You might have to update settings and/or get rid of the CNAME.

It should show up on [xuxy09.github.io/ai-deadlines](http://xuxy09.github.io/ai-deadlines).

More on github pages here: [help.github.com/en/categories/github-pages-basics](https://help.github.com/en/categories/github-pages-basics).

**Comment by xuxy09** [comment]
> You might have to update settings and/or get rid of the CNAME.
> 
> It should show up on [xuxy09.github.io/ai-deadlines](http://xuxy09.github.io/ai-deadlines).
> 
> More on github pages here: [help.github.com/en/categories/github-pages-basics](https://help.github.com/en/categories/github-pages-basics).

Thanks for the reply.

I am not quite sure what the settings are that I need to update.

I have deleted CNAME and now I can find the webpage on xuxy09.github.io/ai-deadlines. But it does not look very nice. There is only a table there without the counting clocks.

**Comment by xuxy09** [comment]
I have also modified the url in _config.yml, but still it does not work.

**Comment by abhshkdz** [comment]
Try changing your `baseurl` to `""`?
