### ISSUE TITLE
No deadlines in http://aideadlin.es?

### ISSUE THREAD

**Issue by miaoshuyu** [abhshkdz/ai-deadlines#175]

**Comment by miaoshuyu** [comment]
![image](https://user-images.githubusercontent.com/26992220/59238424-a9681400-8c30-11e9-9534-a15455948703.png)
There is no deadlines in http://aideadlin.es?

**Comment by abhshkdz** [comment]
Oh no :/ seems to be working fine at my end. Could you tell me which browser / version you're using? And you haven't disabled JavaScript, right?

**Comment by miaoshuyu** [comment]
@abhshkdz  Thanks for your reply! 
My brower:Google. 
version:75.0.3770.80 (64) 
JavaScript: enable

**Comment by abhshkdz** [comment]
I am unable to reproduce it.. if you could send me logs from your browser console, that'd be very helpful.

**Comment by miaoshuyu** [comment]
@ @abhshkdz 
![image](https://user-images.githubusercontent.com/26992220/59332671-58881680-8d29-11e9-8d94-bcd5a466234b.png)
Thanks a lot!  It seems that my network cannot connect to the Internet e.g. google.com

**Comment by abhshkdz** [comment]
How about now? I shifted fonts / js to local copies.

**Comment by miaoshuyu** [comment]
@abhshkdz 
![image](https://user-images.githubusercontent.com/26992220/59397220-62a82480-8dbe-11e9-8123-75e7edd8ebf4.png)
Waaaaa. Ok now! You’re the greatest!! and it is faster to open it.

**Comment by abhshkdz** [comment]
Awesome!
