### ISSUE TITLE
Show H-Index / CORE rating of a conference

### ISSUE THREAD

**Issue by oleg-kachan** [abhshkdz/ai-deadlines#181]
It would be nice to show H-Index and CORE rating for each conference in the list.

**Comment by abhshkdz** [comment]
Good idea; some meta info for each conference would indeed be useful. Will look into it.

**Comment by MilesCranmer** [comment]
Has this been done? I'm about to add it if not

**Comment by MilesCranmer** [comment]
We can automatically scrape information from here: https://scholar.google.com/citations?view_op=top_venues&hl=en

**Comment by MilesCranmer** [comment]
I have added this in the pull request #263.

**Comment by MilesCranmer** [comment]
I haven't added anyway of displaying/ranking the h-index information though. I'm not sure how you would like to do that.

**Comment by MilesCranmer** [comment]
Should these be displayed in the same part as the `note`? Here: https://github.com/abhshkdz/ai-deadlines/blob/c485c14fb862302ef670b35d31a3a874573b838e/_layouts/home.html#L93

**Comment by abhshkdz** [comment]
I was thinking to show it just on the specific [conference pages](https://github.com/abhshkdz/ai-deadlines/blob/gh-pages/_pages/conference.html) (see for e.g. https://aideadlin.es/conference/?id=emnlp20), maybe right below "website", and only for cases where it's not -1.

**Comment by MilesCranmer** [comment]
That's a good idea!
