### ISSUE TITLE
Could you please export the "mandatory abstract" deadlines with the Google Calendar URL?

### ISSUE THREAD

**Issue by amrsharaf** [abhshkdz/ai-deadlines#204]
@abhshkdz Thanks for the great work! I use the google calendar url [here](https://calendar.google.com/calendar/r?cid=http://aideadlin.es/ai-deadlines.ics ) to keep track of conference deadlines, I missed the AAAI abstract deadline and it'd be really great if you can also add the mandatory abstracts deadline to the Google calendar, many thanks!

**Comment by abhshkdz** [comment]
Thanks for the suggestion; hopefully https://github.com/abhshkdz/ai-deadlines/commit/a4cb0838aa470fb2031497bf5344dcbc88a2f623 fixes it.

**Comment by amrsharaf** [comment]
Thank you so much! I see this fixed the .ics file import option, but the google calendar link doesn't seem to include the abstract deadline. I tested importing the .ics file and it works fine, but adding the google calendar from the url doesn't work.

**Comment by abhshkdz** [comment]
It takes a while for Google Calendar to trigger updates to external calendars.

I see it at my end now; could you check again please? If it doesn't show up, maybe try removing and re-adding the calendar.

**Comment by amrsharaf** [comment]
It's working now, thank you so much!
