### ISSUE TITLE
Google Calendar has the wrong / shifted conference deadlines

### ISSUE THREAD

**Issue by amrsharaf** [abhshkdz/ai-deadlines#209]
I was looking at the ACL 2020 and IJCAI deadlines, the deadline on the aideadlines website is correct, but the event on Google Calendar is not correct, it's shifted one day earlier, and set the time to PM instead of AM. 

For example, ACL has a deadline Tuesday, December 10th, 6:59am New York time, but the calendar event is set to Monday, December 9th, 6:59pm. 

I think this is just a PM vs AM issue in data conversion.

**Comment by abhshkdz** [comment]
Oh no! Sounds like a ~major bug. :( Looking into it.

**Comment by amrsharaf** [comment]
Thank you so much for looking into this, I waited for a while to make sure the Google Calendar is updates, but the ACL deadline is still wrong :(

**Comment by amrsharaf** [comment]
@abhshkdz  I think this is still not fixed yet, the ACL deadline was wrong, can we re-open this issue please? Thank you so much!

**Comment by abhshkdz** [comment]
Thanks for flagging this again! Tbh I'm not sure what's wrong in the ics and how to fix this :(

I might try playing around with various parameters a bit.. Let me know if you have suggestions.

**Comment by abhshkdz** [comment]
Looks like https://github.com/abhshkdz/ai-deadlines/issues/220 fixed it. E.g. ACL deadline event looks correct now. Could you check again please?

**Comment by amrsharaf** [comment]
Yes, I think it's fixed now, thank you so much!
