### ISSUE TITLE
ics file is missing line breaks

### ISSUE THREAD

**Issue by ujaya** [abhshkdz/ai-deadlines#220]
The .ics file is missing line breaks in a few of the events, preventing all of the events from importing properly.

**Comment by abhshkdz** [comment]
@ujaya Thanks for pointing this out! Could you please check if https://github.com/abhshkdz/ai-deadlines/commit/e9f2350b389a4af3a0e8b6482051947493327795 fixed it?

**Comment by ujaya** [comment]
Working fine now, thanks.
