### ISSUE TITLE
Can't exactly replicate how the website displays

### ISSUE THREAD

**Issue by bguedj** [abhshkdz/ai-deadlines#254]
Hi @abhshkdz many thanks for a great repo!

I have forked it and very lightly adapted the _config.yml file but I'm very puzzled that the website, although it builds OK, does not display exactly as yours.
Compare [https://bguedj.github.io/ai-deadlines/](https://bguedj.github.io/ai-deadlines/) with [https://aideadlin.es/](https://aideadlin.es/)
What I don't understand: when I build the website locally with `jekyll serve` it looks exactly as yours.
I've searched for hours and the only advice I've found was to update gems, which I've done. No difference.

Any idea why [https://bguedj.github.io/ai-deadlines/](https://bguedj.github.io/ai-deadlines/) displays differently? I should also add that I am using Safari on a Mac.

Any help greatly appreciated :)

<img width="757" alt="Screenshot 2020-04-15 at 22 40 47" src="https://user-images.githubusercontent.com/16050786/79391856-36bf7780-7f6a-11ea-86fb-033e79eaa03c.png">

**Comment by bguedj** [comment]
Nevermind, found the solution -- turns out I was wrongly using `domain` and `baseurl`. All good now!

**Comment by bguedj** [comment]
Reopening the issue as I can't figure out what is triggering it.
My `domain` is `https://bguedj.github.io/` and my `baseurl` is `/ai-deadlines` and I'm still getting this weird looking website (see screenshot). Any clarification on the roles of those two variables would be greatly appreciated :)

**Comment by abhshkdz** [comment]
Hey @bguedj, try setting the `baseurl` in [_config.yml](https://github.com/bguedj/ai-deadlines/blob/gh-pages/_config.yml) to `https://bguedj.github.io/ai-deadlines`.

See [here](https://github.com/abhshkdz/ai-deadlines/blob/gh-pages/_layouts/home.html#L10) for example. `baseurl` gets prepended to css links; and that's currently broken on your website.

**Comment by bguedj** [comment]
Many thanks @abhshkdz for your swift response!

In `_config.yml`, I now have `domain` set to `""` and `baseurl` to `https://bguedj.github.io/ai-deadlines` as you suggested. Website is now back as it should look like (yours).

But I noticed two issues:
- img/calendar does not show up so I suspect some links are still broken -- not sure which ones though...
- refreshing the webpage actually resolves to https://bguedj.github.io/ where it should be https://bguedj.github.io/ai-deadlines -- any thoughts?

Many thanks

**Comment by abhshkdz** [comment]
1) You could change the path to calendar.png [here](https://github.com/bguedj/ai-deadlines/blob/gh-pages/static/js/ouical.min.js).
2) I've messed with `window.history`at several places [here](https://github.com/abhshkdz/ai-deadlines/blob/gh-pages/_layouts/home.html#L245) that you could probably update.

**Comment by bguedj** [comment]
OK, I've solved most problems (by carefully examining occurrences of site.domain and switching to site.baseurl when necessary).

Only issue remaining so far: when visiting [https://bguedj.github.io/ai-deadlines/](https://bguedj.github.io/ai-deadlines/), refreshing the webpage actually resolves to [https://bguedj.github.io](https://bguedj.github.io). Any idea how to change this?

**Comment by abhshkdz** [comment]
That's due to the `window.history` lines: https://github.com/bguedj/ai-deadlines/blob/gh-pages/_layouts/home.html#L245. If you replace all `/?sub` with `/ai-deadlines/?sub`, it should get fixed.

**Comment by bguedj** [comment]
Indeed! Many, many thanks for your kind help!
