### ISSUE TITLE
Support for theory confs

### ISSUE THREAD

**Issue by kirk86** [abhshkdz/ai-deadlines#277]
Could you please add support for the following conferences?

STOC: http://acm-stoc.org/stoc2020/
ISIT: https://2020.ieee-isit.org/
SIAM: https://www.siam.org/conferences/cm/conference/soda21
ICAPS: https://icaps20.icaps-conference.org/
GECCO: https://gecco-2020.sigevo.org/index.html/HomePage
SAT: http://sat2020.idea-researchlab.org/
CP: https://cp2020.a4cp.org/
CCC: https://computationalcomplexity.org/
CADE: https://ijcar2020.org/
ICPO: http://www.lse.ac.uk/IPCO-2020
CPM: http://cpm2020.compute.dtu.dk/
ECTA: http://www.ecta.ijcci.org/
CPAIOR: https://cpaior.org/
FSTTCS: https://www.fsttcs.org.in/2020/
COCOON: http://cocoon-conference.org/2020/index.html
MFCS: http://mfcs.mff.cuni.cz/2020/
GSEC: https://www.gamesec-conf.org/

Thanks!

**Comment by abhshkdz** [comment]
Thanks for the suggestion, but these probably deserve a separate listing outside of aideadlin.es (please feel free to fork and host btw!).

I'm admittedly not from any of the above communities, but from a brief skim, their intersection with AI seems largely incidental and not the primary focus.
