### ISSUE TITLE
unique URLs for unchecked boxes

### ISSUE THREAD

**Issue by soumith** [abhshkdz/ai-deadlines#3]
right now, unchecking some boxes doesn't actually change the URL in any way.

For example, if I only have ML and CV checked, the URL is still http://aideadlin.es/ . 
It would be quite useful when bookmarking to have a unique URL such as http://aideadlin.es/#ML-CV (or something like that) generated in this case.

**Comment by abhshkdz** [comment]
It does preserve state for now if you use the same client (via localstorage). So for example, if you check ML and CV, every time you open the page, it'll have ML and CV checked.

I like the idea of adding in fragments in the URL as well. That would make it shareable/bookmarkable. I'll get around to it. Thanks @soumith!
