### ISSUE TITLE
Support for ISER 

### ISSUE THREAD

**Issue by octopuscabbage** [abhshkdz/ai-deadlines#315]
The ISER deadline for this year has passed but I would like to see this on the website for 2021.

http://iser2020.org/

If this is welcome to add, I will add ISER 2021 once it is announced.

**Comment by abhshkdz** [comment]
Hey @octopuscabbage, I couldn't find ISER [here](https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_robotics) and it doesn't seem to be a top-tier conference as per [conferenceranks.com](http://www.conferenceranks.com/).

To keep the list manageable, I'm only looking to list top-tier conferences for now.
