### ISSUE TITLE
ICCV21 deadline is incorrect

### ISSUE THREAD

**Issue by frostinassiky** [abhshkdz/ai-deadlines#331]
The official deadline closes one hour earlier.

**Comment by CydKnocking** [comment]
Yeah!
The exact deadline is actually 1 hour earlier than demonstrated due to DST on Mar 14...

**Comment by wusize** [comment]
Was there anybody who missed the deadline of submission?

**Comment by abhshkdz** [comment]
:( Crap, I really hope nobody missed their deadline because of this. Turns out I was using an older version of moment.js that had a DST bug..
