### ISSUE TITLE
siggraph and siggraph asia 

### ISSUE THREAD

**Issue by betterze** [abhshkdz/ai-deadlines#340]
Dear Abhishek,

Thank you for your great work, it makes our lives much easier.

Would you mind add [Siggraph](https://s2021.siggraph.org/) and [Siggraph Asia](https://sa2021.siggraph.org/en/) to the list? They are both top conference in computational photography and computer vision.

Thank you very much for your help.

Best Wishes,

Alex

**Comment by abhshkdz** [comment]
Yeah of course, would you mind sending in a pull request please.
