### ISSUE TITLE
Thanks very much. IJCAI expires at Jan 15,2022 for sure？

### ISSUE THREAD

**Issue by xwpaul** [abhshkdz/ai-deadlines#374]
Thanks very much. IJCAI expires at Jan 15,2022 for sure？I have no access to exact date in public. 
PS: I love the app. Could the ddls extend more top conferences, like Sigir, Sigcomm?

**Comment by abhshkdz** [comment]
> IJCAI expires at Jan 15,2022 for sure？I have no access to exact date in public.

Still tentative, but yes: https://ijcai-22.org/dates/

> PS: I love the app. Could the ddls extend more top conferences, like Sigir, Sigcomm?

Thank you! :) sigir — yes — but probably not sigcomm (doesn't seem AI-focused)

**Comment by xwpaul** [comment]
Very helpful. Thank you!

**Comment by entalent** [comment]
The official site of IJCAI (https://ijcai-22.org/calls-papers/) says that the deadline for paper submission is January 14, 2022 (UTC+1), which should be 06:59 AM of January 15, 2022 (in UTC+8 timezone). However, this website shows that the deadline of IJCAI is Jan 15 2022 19:59:59 GMT+0800. Is the time on the website correct?

**Comment by omarsar** [comment]
Hi @entalent. Thanks for bringing this up. You are right. It should be fixed now.
