### ISSUE TITLE
Certificate is not valid: NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by songquanpeng** [abhshkdz/ai-deadlines#393]
![image](https://user-images.githubusercontent.com/39998050/146746072-84574f02-bf21-4c02-b538-c96d9cc88b1d.png)

> This server couldn't prove that it's aideadlin.es; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by omarsar** [comment]
Thanks for reporting. We are looking into this.

**Comment by liurui39660** [comment]
FIrefox reports a similar error SSL_ERROR_BAD_CERT_DOMAIN and shows a Warning: Potential Security Risk Ahead page when trying to access. Looks like you used the certificate for `*.github.com` in `aideadlin.es`.

Firefox Nightly 97.0a1 (2021-12-22) (64-bit)
Windows 10

**Comment by omarsar** [comment]
Issue resolved!
