### ISSUE TITLE
Moving to HTTPS instead of HTTP

### ISSUE THREAD

**Issue by sharan21** [abhshkdz/ai-deadlines#402]
I don't know if this is the appropriate place to post this issue so please excuse me. These days the http://aideadlin.es domain never responds and the site is unreachable. Sometimes it does respond and my browser complains that it is unsafe as it doesn't use HTTPS. I was wondering whether this can be fixed, or if it is an issue from my system's end?

**Comment by Syzygianinfern0** [comment]
Clicking the link from your comment gives me the same "This site can’t be reached" page, but when I click the same link from [here](http://aideadlin.es/) it loads for me and I have no clue how 😂

**Comment by sharan21** [comment]
There was a spelling error in the URL I posted, its been updated now. Anyway It seems to be working for others so I am guessing its a firewall issue in my uni's network. :/

**Comment by omarsar** [comment]
Hi @sharan21 it might be related to the certificate issue on the website. We are currently trying to fix this. Thanks for your patience.

> I don't know if this is the appropriate place to post this issue so please excuse me. These days the http://aideadlin.es domain never responds and the site is unreachable. Sometimes it does respond and my browser complains that it is unsafe as it doesn't use HTTPS. I was wondering whether this can be fixed, or if it is an issue from my system's end?

**Comment by omarsar** [comment]
Issue resolved!
