### ISSUE TITLE
Wrong deadlines in the website

### ISSUE THREAD

**Issue by Srameo** [abhshkdz/ai-deadlines#422]
The ECCV2022 deadline was Mon. March 7, 2022 (8:59PM CET, 11:59AM PST). However, the deadline on the website is one hour later. I believe this will cause trouble for a lot of people. What should the user do if there is an error next time?

**Comment by XuehaiPan** [comment]
Related #390

**Comment by pansanity666** [comment]
Same for me. Sad :(

**Comment by mickelliu** [comment]
Sadge same for me.

**Comment by XuehaiPan** [comment]
The deadline in this repo was shifted with an hour by mistake (8:59PM CET -> 21:59 CET).

https://github.com/paperswithcode/ai-deadlines/blob/cb859e3ced39fa457aadac65dc704c3f53f6230a/_data/conferences.yml#L246-L255

Submission deadline: https://eccv2022.ecva.net/submission/

![ECCV Deadline](https://user-images.githubusercontent.com/16078332/157125378-c61e83d4-2ed4-4863-85d5-388610000485.png)

**Comment by omarsar** [comment]
Hi folks, this was an entry mistake as @XuehaiPan pointed out. Apologies for any inconvenience. The repo is community maintained, so it helps to report it here if you see any mistakes or official updates.

We regularly monitor for changes in official key dates. To avoid this from happening again, we are committing an extra effort every week to double check that all deadlines are accurate and up to date.

I also suggest that you also regularly check the website for in case there are any changes. I think it could also help to label conferences where new update on deadline has occurred. Will look into this if necessary.
