### ISSUE TITLE
Add NLPCC for NLP please.

### ISSUE THREAD

**Issue by liuyijiang1994** [abhshkdz/ai-deadlines#437]
- title: NLPCC
  year: 2022
  id: nlpcc2022# title as lower case + last two digits of year
  full_name: International Conference on Natural Language Processing and Chinese Computing # full conference name
  link: http://tcci.ccf.org.cn/conference/2022/
  deadline: 2022-05-09 23:59
  timezone: Asia/Beijing
  place: Guilin, China
  date: September, 22-25, 2022
  note: Important

**Comment by omarsar** [comment]
Hi, @liuyijiang1994. Do you mind opening a PR for this instead?

**Comment by liuyijiang1994** [comment]
> Hi, @liuyijiang1994. Do you mind opening a PR for this instead?

Good idea! I forgot that!

Thanks!
