### ISSUE TITLE
Do you have any plan for assigning an external committer?

### ISSUE THREAD

**Issue by jungtaekkim** [abhshkdz/ai-deadlines#518]
Hi,

I like this project and I hope that it will keep being maintained well.

But, I think the recent PRs are not accepted due to some reasons.

If you have any plan for assigning an external committer, I would like to do that job.

Thank you again.

**Comment by alexmehta** [comment]
The site is great but it's sad to see the lack of maintainer activity.

**Comment by rstojnic** [comment]
Hi all, sorry for the delay on our side. We've just added @andrewkuanop as a new maintainer and he should be able to make sure everything is merged much faster.
