### ISSUE TITLE
Broken website

### ISSUE THREAD

**Issue by tfederico** [abhshkdz/ai-deadlines#523]
The website appears to be broken

![image](https://user-images.githubusercontent.com/15323014/222742874-a64a6220-0a4b-42e4-9c03-5e9661cc455b.png)

It is also showing the same date for all the conferences after ECAI, including the past ones

**Comment by pulkitverma25** [comment]
Also, the conferences are not sorted by deadlines. They are being shown in the order they are input in _data/conferences.yml.

**Comment by adriancaruana** [comment]
I believe this will fix the issue, but I'm not certain though since I haven't tested it. https://github.com/paperswithcode/ai-deadlines/pull/524

**Comment by rstojnic** [comment]
Seems to be fixed now thanks to @adriancaruana
