### ISSUE TITLE
URLs to filtered results broken recently 

### ISSUE THREAD

**Issue by kcorder** [abhshkdz/ai-deadlines#557]
Hello, I've been enjoying using this site and actually had it set as my new tab page as "https://aideadlin.es/?sub=RO,ML". 
However within the past few days this link no longer filters by subcategories "Robotics" & "Machine Learning"; instead it shows the full list, and the user must select the subcategories again. Unfortunately this makes it not very useful as a new tab page (maybe I'm the only one). 

You can check this by selecting subcategories, and see that the url is changed accordingly. But if you refresh the page, these filters are no longer preserved. 

I looked at commits from the past week, but only saw updates to "conferences.yml", so I'm not sure what's happened unfortunately :/

**Comment by andrewkuanop** [comment]
Thanks for reporting! I believed this issue has since been solved.
