### ISSUE TITLE
hci-deadlines site not found

### ISSUE THREAD

**Issue by cllei12** [abhshkdz/ai-deadlines#641]
[hci-deadlines.github.io (Human-Computer Interaction conferences)](https://hci-deadlines.github.io/) are not found.

https://github.com/paperswithcode/ai-deadlines/blob/dfc6a47d7c405d3f2ac55646221fb6711709120a/README.md?plain=1#L56

https://github.com/paperswithcode/ai-deadlines/blob/dfc6a47d7c405d3f2ac55646221fb6711709120a/README.md?plain=1#L82

**Comment by andrewkuanop** [comment]
Hi thanks for letting us know but you might need to contact @makinteract about this.
