### ISSUE TITLE
Website Content Error

### ISSUE THREAD

**Issue by Cb1ock** [abhshkdz/ai-deadlines#672]
# When I opened the website today, it displayed like this:
![image](https://github.com/paperswithcode/ai-deadlines/assets/90198143/a0f61870-322e-4dcf-8c4b-e3a64047ccfa)
# The website didn’t display the date it is supposed to show. Is this an issue with my network, or is everyone experiencing this?

**Comment by heitorrapela** [comment]
Same here; I think it was the last update.

**Comment by snoop2head** [comment]
Same here
