### ISSUE TITLE
Button to add all deadlines

### ISSUE THREAD

**Issue by alok** [abhshkdz/ai-deadlines#68]
Since my life isn't stressful enough, apparently, is there a way to add *all* the deadlines to your calendar in one click and subscribe to any new additions?

**Comment by abhshkdz** [comment]
:) Why would you do that to yourself?!

**Comment by alok** [comment]
Because it's easier for me to add everything and just delete the ones I don't want than looking at this page every few months.

**Comment by abhshkdz** [comment]
I was mostly kidding when I asked that, I don't have a way to add all right now, I'll look into it. Thanks for the suggestion!

**Comment by rszeto** [comment]
My PR request does this! https://github.com/abhshkdz/ai-deadlines/pull/121

**Comment by abhshkdz** [comment]
f2f9c35 implements this.
