### ISSUE TITLE
WACV 2025

### ISSUE THREAD

**Issue by sxyxs** [abhshkdz/ai-deadlines#682]
Hi,

Seems wacv2025 Round1 released DDL. Paper submissions: July 15th (Monday).

Check https://wacv2025.thecvf.com/

**Comment by silence-tang** [comment]
> Hi,
> 
> Seems wacv2025 Round1 released DDL. Paper submissions: July 15th (Monday).
> 
> Check https://wacv2025.thecvf.com/

Hi, may I ask how to submit to wacv 2025? I didn't find the link to paper submission. Thanks!

**Comment by opeyemibami** [comment]
Hi @silence-tang, here is the link I found for WACV 2025 paper submission 
https://cmt3.research.microsoft.com/User/Login?ReturnUrl=%2FWACV2025
