### ISSUE TITLE
Medical image conference / special issue

### ISSUE THREAD

**Issue by duducheng** [abhshkdz/ai-deadlines#94]
Hello, 

Thanks for your nice work, I would like to conbritute some medical image analysis conference / special issues of some important journels. 

Shall I contribute a type "Medical Image Analysis / MIA" in "types.yml", or just contribute them to "Computer Vision" tag?

**Comment by abhshkdz** [comment]
Sorry, to keep things minimal and manageable, I'm only looking to list top-tier conferences in AI here. :( 

Please feel free to maintain a fork to list conferences of interest to you.
